spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cart_and_cook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080/realms/cart_and_cook}

# Server settings
server:
  port: ${PORT:8081}
